---
grubInstall:
  - grub-install
  - grub-mkconfig
efiBootloader: "grub"
kernel: "/boot/vmlinuz"
img: "/boot/initramfs-linux.img"
grubCfg: "/boot/grub/grub.cfg"
grubMkconfig: "/usr/bin/grub-mkconfig"
grubMkconfigTarget: "/boot/grub/grub.cfg"
useSplash: true
theme: "/usr/share/grub/themes/kore/theme.txt"
