---
keyboardModels:
  - pc105
  - pc104
  - pc102
  - pc101
  - pc98
  - macintosh
  - macintosh_old
  - azerty
  - sun
  - apple
  - thinkpad
  - hp
  - dell
  - macbook78
  - macbook79
  - macbookpro
xkbOptions:
  - grp:alt_shift_toggle
  - grp:ctrl_shift_toggle
  - grp:lalt_shift_toggle
  - grp:lwin_switch
  - grp:rwin_switch
  - terminate:ctrl_alt_bksp
  - lv3:ralt_switch
  - lv3:rwin_switch
  - lv3:lwin_switch
  - lv3:alt_switch
  - lv3:menu_switch
  - compose:rwin
  - compose:rctrl
  - compose:lwin
  - compose:lctrl
  - compose:ralt
  - compose:ralt
  - compose:menu
  - keypad:pointerkeys
  - keypad:navigate
  - caps:swapescape
  - caps:escape
  - ctrl:nocaps
  - altwin:swap_lalt_lwin
