---
defaultFileSystemType: "ext4"
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: "erase"
drawNestedPartitions: false
enableEncryptionWidget: true
enableLuksAutomount: true
partitionLayout:
  - name: "efi"
    type: "512MiB"
    fileSystem: "fat32"
    mountPoint: "/boot"
    attributes: ["boot"]
  - name: "root"
    type: "100%"
    fileSystem: "btrfs"
    mountPoint: "/"
    features:
      - "compress=zstd"
      - "noatime"
  - name: "swap"
    type: "4GiB"
    fileSystem: "linuxswap"
