---
actions:
  - command: "systemctl enable sddm"
    script: false
  - command: "systemctl enable NetworkManager"
    script: false
  - command: "systemctl enable bluetooth"
    script: false
  - command: "systemctl enable ufw"
    script: false
  - command: "systemctl enable apparmor"
    script: false
  - command: "systemctl enable fail2ban"
    script: false
  - command: "systemctl enable auditd"
    script: false
  - command: "systemctl enable systemd-resolved"
    script: false
  - command: "ufw --force enable"
    script: false
  - command: "plymouth-set-default-theme -R kore"
    script: false
  - command: "kwriteconfig5 --file /etc/sddm.conf --group Theme --key Current kore"
    script: false
  - command: "lookandfeeltool -a org.kore.plasma.desktop"
    script: false
