---
userGroup:
  - sudo
  - storage
  - power
  - audio
  - video
  - input
  - optical
  - lp
  - scanner
  - kvm
  - libvirt
  - docker

autologinGroup:  false
doAutologin:      false
sudoersGroup:     sudo
passwordAction:   "set"
setRootPassword:  true
doReusePassword:  false
preserve:
  - "root"
defaultGroups:
  - sudo
  - storage
  - power
  - audio
  - video
  - input
  - optical
