---
welcomeStyle:         "sidebar"
showSupportUrl:       true
showKnownIssuesUrl:   true
showReleaseNotesUrl:  true
requirements:
  required:
    - ram
    - storage
    - internet
    - root
  requiredStorage:    8
  requiredRam:        2.0
  internetCheckUrl:   "https://wsgpolar.me"
  check:
    storage:
      name:     "storage"
      required: 8
    ram:
      name:     "ram"
      required: 2.0
    internet:
      name:     "internet"
      required: false
    root:
      name:     "root"
      required: true
