[Autologin]
Session=plasmawayland
User=kore
Relogin=false

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
Numlock=on

[Theme]
Current=kore
CursorTheme=breeze_cursors
Font=JetBrains Mono,10,-1,5,50,0,0,0,0,0,Regular

[Users]
MaximumUid=65000
MinimumUid=1000
HideShells=/sbin/nologin,/bin/false,/usr/bin/nologin
HideUsers=

[X11]
DisplayCommand=/usr/share/sddm/scripts/startx
SessionCommand=/usr/share/sddm/scripts/startwayland
